export type DialCountry = { iso: string; name: string; dial: string };

// Indicatifs téléphoniques internationaux (noms en français). La Tunisie est
// le pays par défaut du formulaire.
export const DEFAULT_DIAL_ISO = "TN";

export const DIAL_COUNTRIES: DialCountry[] = [
  { iso: "TN", name: "Tunisie", dial: "+216" },
  { iso: "DZ", name: "Algérie", dial: "+213" },
  { iso: "MA", name: "Maroc", dial: "+212" },
  { iso: "LY", name: "Libye", dial: "+218" },
  { iso: "FR", name: "France", dial: "+33" },
  { iso: "AF", name: "Afghanistan", dial: "+93" },
  { iso: "ZA", name: "Afrique du Sud", dial: "+27" },
  { iso: "AL", name: "Albanie", dial: "+355" },
  { iso: "DE", name: "Allemagne", dial: "+49" },
  { iso: "AD", name: "Andorre", dial: "+376" },
  { iso: "AO", name: "Angola", dial: "+244" },
  { iso: "SA", name: "Arabie saoudite", dial: "+966" },
  { iso: "AR", name: "Argentine", dial: "+54" },
  { iso: "AM", name: "Arménie", dial: "+374" },
  { iso: "AU", name: "Australie", dial: "+61" },
  { iso: "AT", name: "Autriche", dial: "+43" },
  { iso: "AZ", name: "Azerbaïdjan", dial: "+994" },
  { iso: "BH", name: "Bahreïn", dial: "+973" },
  { iso: "BD", name: "Bangladesh", dial: "+880" },
  { iso: "BE", name: "Belgique", dial: "+32" },
  { iso: "BJ", name: "Bénin", dial: "+229" },
  { iso: "BY", name: "Biélorussie", dial: "+375" },
  { iso: "BO", name: "Bolivie", dial: "+591" },
  { iso: "BA", name: "Bosnie-Herzégovine", dial: "+387" },
  { iso: "BW", name: "Botswana", dial: "+267" },
  { iso: "BR", name: "Brésil", dial: "+55" },
  { iso: "BN", name: "Brunei", dial: "+673" },
  { iso: "BG", name: "Bulgarie", dial: "+359" },
  { iso: "BF", name: "Burkina Faso", dial: "+226" },
  { iso: "BI", name: "Burundi", dial: "+257" },
  { iso: "KH", name: "Cambodge", dial: "+855" },
  { iso: "CM", name: "Cameroun", dial: "+237" },
  { iso: "CA", name: "Canada", dial: "+1" },
  { iso: "CV", name: "Cap-Vert", dial: "+238" },
  { iso: "CF", name: "Centrafrique", dial: "+236" },
  { iso: "CL", name: "Chili", dial: "+56" },
  { iso: "CN", name: "Chine", dial: "+86" },
  { iso: "CY", name: "Chypre", dial: "+357" },
  { iso: "CO", name: "Colombie", dial: "+57" },
  { iso: "KM", name: "Comores", dial: "+269" },
  { iso: "CG", name: "Congo", dial: "+242" },
  { iso: "CD", name: "Congo (RDC)", dial: "+243" },
  { iso: "KR", name: "Corée du Sud", dial: "+82" },
  { iso: "CR", name: "Costa Rica", dial: "+506" },
  { iso: "CI", name: "Côte d'Ivoire", dial: "+225" },
  { iso: "HR", name: "Croatie", dial: "+385" },
  { iso: "CU", name: "Cuba", dial: "+53" },
  { iso: "DK", name: "Danemark", dial: "+45" },
  { iso: "DJ", name: "Djibouti", dial: "+253" },
  { iso: "EG", name: "Égypte", dial: "+20" },
  { iso: "AE", name: "Émirats arabes unis", dial: "+971" },
  { iso: "EC", name: "Équateur", dial: "+593" },
  { iso: "ER", name: "Érythrée", dial: "+291" },
  { iso: "ES", name: "Espagne", dial: "+34" },
  { iso: "EE", name: "Estonie", dial: "+372" },
  { iso: "US", name: "États-Unis", dial: "+1" },
  { iso: "ET", name: "Éthiopie", dial: "+251" },
  { iso: "FI", name: "Finlande", dial: "+358" },
  { iso: "GA", name: "Gabon", dial: "+241" },
  { iso: "GM", name: "Gambie", dial: "+220" },
  { iso: "GE", name: "Géorgie", dial: "+995" },
  { iso: "GH", name: "Ghana", dial: "+233" },
  { iso: "GR", name: "Grèce", dial: "+30" },
  { iso: "GT", name: "Guatemala", dial: "+502" },
  { iso: "GN", name: "Guinée", dial: "+224" },
  { iso: "GQ", name: "Guinée équatoriale", dial: "+240" },
  { iso: "GW", name: "Guinée-Bissau", dial: "+245" },
  { iso: "HT", name: "Haïti", dial: "+509" },
  { iso: "HN", name: "Honduras", dial: "+504" },
  { iso: "HK", name: "Hong Kong", dial: "+852" },
  { iso: "HU", name: "Hongrie", dial: "+36" },
  { iso: "IN", name: "Inde", dial: "+91" },
  { iso: "ID", name: "Indonésie", dial: "+62" },
  { iso: "IQ", name: "Irak", dial: "+964" },
  { iso: "IR", name: "Iran", dial: "+98" },
  { iso: "IE", name: "Irlande", dial: "+353" },
  { iso: "IS", name: "Islande", dial: "+354" },
  { iso: "IT", name: "Italie", dial: "+39" },
  { iso: "JM", name: "Jamaïque", dial: "+1876" },
  { iso: "JP", name: "Japon", dial: "+81" },
  { iso: "JO", name: "Jordanie", dial: "+962" },
  { iso: "KZ", name: "Kazakhstan", dial: "+7" },
  { iso: "KE", name: "Kenya", dial: "+254" },
  { iso: "KG", name: "Kirghizistan", dial: "+996" },
  { iso: "XK", name: "Kosovo", dial: "+383" },
  { iso: "KW", name: "Koweït", dial: "+965" },
  { iso: "LA", name: "Laos", dial: "+856" },
  { iso: "LS", name: "Lesotho", dial: "+266" },
  { iso: "LV", name: "Lettonie", dial: "+371" },
  { iso: "LB", name: "Liban", dial: "+961" },
  { iso: "LR", name: "Liberia", dial: "+231" },
  { iso: "LI", name: "Liechtenstein", dial: "+423" },
  { iso: "LT", name: "Lituanie", dial: "+370" },
  { iso: "LU", name: "Luxembourg", dial: "+352" },
  { iso: "MO", name: "Macao", dial: "+853" },
  { iso: "MK", name: "Macédoine du Nord", dial: "+389" },
  { iso: "MG", name: "Madagascar", dial: "+261" },
  { iso: "MY", name: "Malaisie", dial: "+60" },
  { iso: "MW", name: "Malawi", dial: "+265" },
  { iso: "MV", name: "Maldives", dial: "+960" },
  { iso: "ML", name: "Mali", dial: "+223" },
  { iso: "MT", name: "Malte", dial: "+356" },
  { iso: "MU", name: "Maurice", dial: "+230" },
  { iso: "MR", name: "Mauritanie", dial: "+222" },
  { iso: "MX", name: "Mexique", dial: "+52" },
  { iso: "MD", name: "Moldavie", dial: "+373" },
  { iso: "MC", name: "Monaco", dial: "+377" },
  { iso: "MN", name: "Mongolie", dial: "+976" },
  { iso: "ME", name: "Monténégro", dial: "+382" },
  { iso: "MZ", name: "Mozambique", dial: "+258" },
  { iso: "MM", name: "Myanmar", dial: "+95" },
  { iso: "NA", name: "Namibie", dial: "+264" },
  { iso: "NP", name: "Népal", dial: "+977" },
  { iso: "NI", name: "Nicaragua", dial: "+505" },
  { iso: "NE", name: "Niger", dial: "+227" },
  { iso: "NG", name: "Nigeria", dial: "+234" },
  { iso: "NO", name: "Norvège", dial: "+47" },
  { iso: "NZ", name: "Nouvelle-Zélande", dial: "+64" },
  { iso: "OM", name: "Oman", dial: "+968" },
  { iso: "UG", name: "Ouganda", dial: "+256" },
  { iso: "UZ", name: "Ouzbékistan", dial: "+998" },
  { iso: "PK", name: "Pakistan", dial: "+92" },
  { iso: "PS", name: "Palestine", dial: "+970" },
  { iso: "PA", name: "Panama", dial: "+507" },
  { iso: "PY", name: "Paraguay", dial: "+595" },
  { iso: "NL", name: "Pays-Bas", dial: "+31" },
  { iso: "PE", name: "Pérou", dial: "+51" },
  { iso: "PH", name: "Philippines", dial: "+63" },
  { iso: "PL", name: "Pologne", dial: "+48" },
  { iso: "PT", name: "Portugal", dial: "+351" },
  { iso: "QA", name: "Qatar", dial: "+974" },
  { iso: "DO", name: "République dominicaine", dial: "+1809" },
  { iso: "CZ", name: "République tchèque", dial: "+420" },
  { iso: "RO", name: "Roumanie", dial: "+40" },
  { iso: "GB", name: "Royaume-Uni", dial: "+44" },
  { iso: "RU", name: "Russie", dial: "+7" },
  { iso: "RW", name: "Rwanda", dial: "+250" },
  { iso: "SM", name: "Saint-Marin", dial: "+378" },
  { iso: "SV", name: "Salvador", dial: "+503" },
  { iso: "SN", name: "Sénégal", dial: "+221" },
  { iso: "RS", name: "Serbie", dial: "+381" },
  { iso: "SL", name: "Sierra Leone", dial: "+232" },
  { iso: "SG", name: "Singapour", dial: "+65" },
  { iso: "SK", name: "Slovaquie", dial: "+421" },
  { iso: "SI", name: "Slovénie", dial: "+386" },
  { iso: "SO", name: "Somalie", dial: "+252" },
  { iso: "SD", name: "Soudan", dial: "+249" },
  { iso: "SS", name: "Soudan du Sud", dial: "+211" },
  { iso: "LK", name: "Sri Lanka", dial: "+94" },
  { iso: "SE", name: "Suède", dial: "+46" },
  { iso: "CH", name: "Suisse", dial: "+41" },
  { iso: "SY", name: "Syrie", dial: "+963" },
  { iso: "TJ", name: "Tadjikistan", dial: "+992" },
  { iso: "TW", name: "Taïwan", dial: "+886" },
  { iso: "TZ", name: "Tanzanie", dial: "+255" },
  { iso: "TD", name: "Tchad", dial: "+235" },
  { iso: "TH", name: "Thaïlande", dial: "+66" },
  { iso: "TG", name: "Togo", dial: "+228" },
  { iso: "TT", name: "Trinité-et-Tobago", dial: "+1868" },
  { iso: "TM", name: "Turkménistan", dial: "+993" },
  { iso: "TR", name: "Turquie", dial: "+90" },
  { iso: "UA", name: "Ukraine", dial: "+380" },
  { iso: "UY", name: "Uruguay", dial: "+598" },
  { iso: "VE", name: "Venezuela", dial: "+58" },
  { iso: "VN", name: "Viêt Nam", dial: "+84" },
  { iso: "YE", name: "Yémen", dial: "+967" },
  { iso: "ZM", name: "Zambie", dial: "+260" },
  { iso: "ZW", name: "Zimbabwe", dial: "+263" }
];
